# mathematical operation
x = int(input("enter any number"))
y = int(input("enter another number"))
print(x,"+",y,"=",x+y)
print(x,"-",y,"=",x-y)
print(x,"*",y,"=",x*y)
print(x,"/",y,"=",x/y)
print(x,"%",y,"=",x%y)
print(x,"//",y,"=",x//y)
print(x,"**",y,"=",x**y)